/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 player.glb --types --keep-groups 
*/

import * as THREE from "three";
import { useMemo, useRef, type JSX, type ReactNode } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF, useTexture } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import { getModelURL } from "@/utils/resources";

type Player3DProps = JSX.IntrinsicElements["group"] & {
  headRotation?: [number, number, number];
  helmetActive?: boolean;
  chestplateActive?: boolean;
  leggingsActive?: boolean;
  bootsActive?: boolean;
};

type GLTFResult = GLTF & {
  nodes: {
    head_1: THREE.Mesh;
    headwear_1: THREE.Mesh;
    body_1: THREE.Mesh;
    jacket_1: THREE.Mesh;
    left_arm_1: THREE.Mesh;
    left_sleeve_1: THREE.Mesh;
    right_arm_1: THREE.Mesh;
    right_sleeve_1: THREE.Mesh;
    left_leg_1: THREE.Mesh;
    left_pants_1: THREE.Mesh;
    right_leg_1: THREE.Mesh;
    right_pants_1: THREE.Mesh;
    head_2: THREE.Mesh;
    head_3: THREE.Mesh;
    body_2: THREE.Mesh;
    left_shoe_1: THREE.Mesh;
    right_shoe_1: THREE.Mesh;
    left_arm_2: THREE.Mesh;
    right_arm_2: THREE.Mesh;
    waist_1: THREE.Mesh;
    left_leg_2: THREE.Mesh;
    right_leg_2: THREE.Mesh;
  };
  materials: {};
  animations: THREE.AnimationClip[];
};

type AnimatedRotationGroupProps = {
  position: [number, number, number];
  rotationTarget?: [number, number, number];
  children: ReactNode;
};

function AnimatedRotationGroup({
  position,
  rotationTarget = [0, 0, 0],
  children,
}: AnimatedRotationGroupProps) {
  const groupRef = useRef<THREE.Group>(null);
  const currentRotation = useRef<[number, number, number]>([0, 0, 0]);

  useFrame((_, delta) => {
    const damping = 1 - Math.exp(-delta * 12);

    currentRotation.current[0] = THREE.MathUtils.lerp(
      currentRotation.current[0],
      rotationTarget[0],
      damping
    );
    currentRotation.current[1] = THREE.MathUtils.lerp(
      currentRotation.current[1],
      rotationTarget[1],
      damping
    );
    currentRotation.current[2] = THREE.MathUtils.lerp(
      currentRotation.current[2],
      rotationTarget[2],
      damping
    );

    if (groupRef.current) {
      groupRef.current.rotation.set(...currentRotation.current);
    }
  });

  return (
    <group ref={groupRef} position={position}>
      {children}
    </group>
  );
}

export function Player3D({
  headRotation,
  helmetActive,
  chestplateActive,
  leggingsActive,
  bootsActive,
  ...props
}: Player3DProps) {
  const { nodes } = useGLTF(getModelURL("player.glb")) as unknown as GLTFResult;

  const textures = useTexture([
    getModelURL("textures/skin.png"),
    getModelURL("textures/armor_layer_1.png"),
    getModelURL("textures/armor_layer_2.png"),
  ]);

  const materials = useMemo(() => {
    return textures.map(texture => {
      texture.colorSpace = THREE.SRGBColorSpace;
      texture.flipY = false;
      texture.magFilter = THREE.NearestFilter;
      texture.minFilter = THREE.NearestFilter;

      return new THREE.MeshStandardMaterial({
        map: texture,
        roughness: 1,
        metalness: 0,
        transparent: true,
        alphaTest: 0.01,
      });
    });
  }, [textures]);

  const [skin, layer_1, layer_2] = materials;

  return (
    <group {...props} dispose={null}>
      <AnimatedRotationGroup position={[0, 1.5, 0]} rotationTarget={headRotation}>
        <mesh geometry={nodes.head_1.geometry} material={skin} position={[0, -1.5, 0]} />
      </AnimatedRotationGroup>
      <AnimatedRotationGroup position={[0, 1.5, 0]} rotationTarget={headRotation}>
        <mesh geometry={nodes.headwear_1.geometry} material={skin} position={[0, -1.5, 0]} />
      </AnimatedRotationGroup>
      <group position={[0, 1.5, 0]}>
        <mesh geometry={nodes.body_1.geometry} material={skin} position={[0, -1.5, 0]} />
      </group>
      <group position={[0, 1.5, 0]}>
        <mesh geometry={nodes.jacket_1.geometry} material={skin} position={[0, -1.5, 0]} />
      </group>
      <group position={[-0.313, 1.375, 0]}>
        <mesh geometry={nodes.left_arm_1.geometry} material={skin} position={[0.313, -1.375, 0]} />
      </group>
      <group position={[-0.313, 1.375, 0]}>
        <mesh
          geometry={nodes.left_sleeve_1.geometry}
          material={skin}
          position={[0.313, -1.375, 0]}
        />
      </group>
      <group position={[0.313, 1.375, 0]}>
        <mesh
          geometry={nodes.right_arm_1.geometry}
          material={skin}
          position={[-0.313, -1.375, 0]}
        />
      </group>
      <group position={[0.313, 1.375, 0]}>
        <mesh
          geometry={nodes.right_sleeve_1.geometry}
          material={skin}
          position={[-0.313, -1.375, 0]}
        />
      </group>
      <group position={[-0.125, 0.75, 0]}>
        <mesh geometry={nodes.left_leg_1.geometry} material={skin} position={[0.125, -0.75, 0]} />
      </group>
      <group position={[-0.125, 0.75, 0]}>
        <mesh geometry={nodes.left_pants_1.geometry} material={skin} position={[0.125, -0.75, 0]} />
      </group>
      <group position={[0.125, 0.75, 0]}>
        <mesh geometry={nodes.right_leg_1.geometry} material={skin} position={[-0.125, -0.75, 0]} />
      </group>
      <group position={[0.125, 0.75, 0]}>
        <mesh
          geometry={nodes.right_pants_1.geometry}
          material={skin}
          position={[-0.125, -0.75, 0]}
        />
      </group>
      <group position={[0, 1.5, 0]}>
        {bootsActive && (
          <>
            <group position={[-0.119, -0.75, 0]}>
              <mesh
                geometry={nodes.left_shoe_1.geometry}
                material={layer_1}
                position={[0.119, -0.75, 0]}
              />
            </group>
            <group position={[0.119, -0.75, 0]}>
              <mesh
                geometry={nodes.right_shoe_1.geometry}
                material={layer_1}
                position={[-0.119, -0.75, 0]}
              />
            </group>
          </>
        )}
        {chestplateActive && (
          <>
            <group position={[-0.313, -0.125, 0]}>
              <mesh
                geometry={nodes.left_arm_2.geometry}
                material={layer_1}
                position={[0.313, -1.375, 0]}
              />
            </group>
            <group position={[0.313, -0.125, 0]}>
              <mesh
                geometry={nodes.right_arm_2.geometry}
                material={layer_1}
                position={[-0.313, -1.375, 0]}
              />
            </group>
            <mesh geometry={nodes.body_2.geometry} material={layer_1} position={[0, -1.5, 0]} />
          </>
        )}
        {leggingsActive && (
          <>
            <group position={[-0.119, -0.75, 0]}>
              <mesh
                geometry={nodes.left_leg_2.geometry}
                material={layer_2}
                position={[0.119, -0.75, 0]}
              />
            </group>
            <group position={[0.119, -0.75, 0]}>
              <mesh
                geometry={nodes.right_leg_2.geometry}
                material={layer_2}
                position={[-0.119, -0.75, 0]}
              />
            </group>
            <mesh geometry={nodes.waist_1.geometry} material={layer_2} position={[0, -1.5, 0]} />
          </>
        )}
        {helmetActive && (
          <>
            <AnimatedRotationGroup position={[0, 0, 0]} rotationTarget={headRotation}>
              <mesh geometry={nodes.head_2.geometry} material={layer_1} position={[0, -1.5, 0]} />
              <mesh geometry={nodes.head_3.geometry} material={layer_1} position={[0, -1.5, 0]} />
            </AnimatedRotationGroup>
          </>
        )}
      </group>
    </group>
  );
}

useGLTF.preload(getModelURL("player.glb"));
